---
- name: Install mongodb
  become: yes
  package:
    name: mongodb-server
    state: installed
- name: enable mongodb
  become: yes
  service:
    name: mongod
    enabled: yes
    state: started